# Generated by Django 4.2 on 2023-05-14 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.CharField(max_length=50)),
                ('patientName', models.CharField(max_length=100)),
                ('patientTell', models.CharField(max_length=100)),
                ('paientAge', models.IntegerField()),
                ('testType', models.CharField(max_length=100)),
                ('patientGenter', models.CharField(max_length=100)),
                ('patientAddress', models.CharField(max_length=100)),
                ('patientRegDate', models.DateTimeField(auto_now_add=True)),
                ('patientXrayImage', models.ImageField(upload_to='xray')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
