# Generated by Django 4.2 on 2023-05-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('patientID', models.CharField(max_length=50)),
                ('patientName', models.CharField(max_length=100)),
                ('patientTell', models.CharField(max_length=100)),
                ('paientAge', models.IntegerField()),
                ('pridected', models.CharField(max_length=100)),
                ('patientGenter', models.CharField(max_length=100)),
                ('patientAddress', models.CharField(max_length=100)),
                ('patientRegDate', models.DateTimeField(auto_now_add=True)),
                ('patientXrayImage', models.ImageField(upload_to='PN/Pneumonia')),
            ],
        ),
        migrations.CreateModel(
            name='NormalTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('patientID', models.CharField(max_length=50)),
                ('patientName', models.CharField(max_length=100)),
                ('patientTell', models.CharField(max_length=100)),
                ('paientAge', models.IntegerField()),
                ('pridected', models.CharField(max_length=100)),
                ('patientGenter', models.CharField(max_length=100)),
                ('patientAddress', models.CharField(max_length=100)),
                ('patientRegDate', models.DateTimeField(auto_now_add=True)),
                ('patientXrayImage', models.ImageField(upload_to='TB/Normal')),
            ],
        ),
        migrations.CreateModel(
            name='Pneumonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('patientID', models.CharField(max_length=50)),
                ('patientName', models.CharField(max_length=100)),
                ('patientTell', models.CharField(max_length=100)),
                ('paientAge', models.IntegerField()),
                ('pridected', models.CharField(max_length=100)),
                ('patientGenter', models.CharField(max_length=100)),
                ('patientAddress', models.CharField(max_length=100)),
                ('patientRegDate', models.DateTimeField(auto_now_add=True)),
                ('patientXrayImage', models.ImageField(upload_to='PN/Pneumonia')),
            ],
        ),
        migrations.CreateModel(
            name='Tuberculosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('patientID', models.CharField(max_length=50)),
                ('patientName', models.CharField(max_length=100)),
                ('patientTell', models.CharField(max_length=100)),
                ('paientAge', models.IntegerField()),
                ('pridected', models.CharField(max_length=100)),
                ('patientGenter', models.CharField(max_length=100)),
                ('patientAddress', models.CharField(max_length=100)),
                ('patientRegDate', models.DateTimeField(auto_now_add=True)),
                ('patientXrayImage', models.ImageField(upload_to='TB/Tuberculosis')),
            ],
        ),
    ]
