# Generated by Django 4.1.7 on 2023-03-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.CharField(max_length=50)),
                ('patientName', models.CharField(max_length=100)),
                ('patientTell', models.CharField(max_length=100)),
                ('paientAge', models.IntegerField()),
                ('patientGenter', models.CharField(max_length=100)),
                ('patientAddress', models.CharField(max_length=100)),
                ('patientRegDate', models.DateTimeField(auto_now_add=True)),
                ('patientXrayImage', models.ImageField(upload_to='xray')),
            ],
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
