# Generated by Django 4.1.7 on 2023-03-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_patient_delete_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('emal', models.CharField(max_length=100)),
                ('tell', models.CharField(max_length=100)),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
