# Generated by Django 4.2 on 2023-05-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_normalpn_normaltb_pneumonia_tuberculosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalpn',
            name='userName',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='normaltb',
            name='userName',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pneumonia',
            name='userName',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tuberculosis',
            name='userName',
            field=models.IntegerField(),
        ),
    ]
