# Generated by Django 4.2 on 2023-05-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_normalpn_username_alter_normaltb_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalpn',
            name='patientID',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='normaltb',
            name='patientID',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientID',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pneumonia',
            name='patientID',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tuberculosis',
            name='patientID',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
