# Generated by Django 4.2 on 2023-05-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_normalpn_patientid_alter_normaltb_patientid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientID',
            field=models.CharField(max_length=50),
        ),
    ]
