# Generated by Django 4.2 on 2023-05-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_patient_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientID',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
