# Generated by Django 4.2 on 2023-05-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_patient_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuberculosis',
            name='patientRegDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
