# Generated by Django 4.2 on 2023-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_tuberculosis_patientregdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientRegDate',
            field=models.DateTimeField(),
        ),
    ]
