# Generated by Django 4.2 on 2023-05-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_patient_patientregdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NormalPN',
            new_name='PneumoniaTests',
        ),
        migrations.RenameModel(
            old_name='Tuberculosis',
            new_name='TuberculosisTests',
        ),
        migrations.DeleteModel(
            name='NormalTB',
        ),
        migrations.DeleteModel(
            name='Pneumonia',
        ),
    ]
