# Generated by Django 4.2 on 2023-05-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_rename_normalpn_pneumoniatests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='isPridicted',
            field=models.BooleanField(default=False),
        ),
    ]
