# Generated by Django 4.2 on 2023-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_patient_ispridicted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='region',
            field=models.CharField(default='Hiiraan', max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pneumoniatests',
            name='region',
            field=models.CharField(default='Hiiraan', max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuberculosistests',
            name='region',
            field=models.CharField(default='Hiiraan', max_length=900),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientRegDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
