# Generated by Django 4.2 on 2023-06-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_patient_region_pneumoniatests_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pneumoniatests',
            name='patientID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tuberculosistests',
            name='patientID',
            field=models.CharField(max_length=50),
        ),
    ]
