# Generated by Django 4.2 on 2023-07-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_patient_patientid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pneumoniatests',
            name='userName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tuberculosistests',
            name='userName',
            field=models.CharField(max_length=50),
        ),
    ]
