# Generated by Django 4.2 on 2023-07-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_pneumoniatests_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientRegDate',
            field=models.DateTimeField(),
        ),
    ]
