# Generated by Django 4.2 on 2023-07-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_pneumoniatests_patientxrayimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientRegDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pneumoniatests',
            name='patientXrayImage',
            field=models.ImageField(upload_to='Pneumonia'),
        ),
        migrations.AlterField(
            model_name='tuberculosistests',
            name='patientXrayImage',
            field=models.ImageField(upload_to='Tuberculosis'),
        ),
    ]
