# Generated by Django 4.2 on 2023-08-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_indivitualuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='indivitualuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
