# Generated by Django 4.2 on 2023-08-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_indivitualuser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='indivitualuser',
            name='name',
            field=models.CharField(default='ahmed', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indivitualuser',
            name='tell',
            field=models.CharField(default='123455', max_length=200),
            preserve_default=False,
        ),
    ]
